### ISSUE TITLE
install issue on npm 5.3

### ISSUE THREAD

**Issue by niahmiah** [cnnlabs/cnn-messaging#19]
These is a known issue in npm 5.3 that prevents this from installing correctly.

npm install -g npm@5.4 fixes this.

Leaving this here for sanity.

**Comment by dsover** [comment]
ran into this issue as well well when running in docker from node 8.4.0 as npm 5.3 is what is packaged. I needed to use yarn to update npm. 

RUN yarn global add npm@5.4.2

**Comment by niahmiah** [comment]
Upgrading to Node 8 LTS should fix this. Closing issue.
