### ISSUE TITLE
2.* clients can crash 3.0.0 subscribers with malformed messages

### ISSUE THREAD

**Issue by tombrake** [cnnlabs/cnn-messaging#28]
If a 2.* client sends a message with an invalid action type, i.e.one not enumerated in actions of https://github.com/cnnlabs/cnn-messaging/blob/master/src/message.js#L8 in 3.0.0, a 3.0.0 subscriber will crash and drop connection (see: https://github.com/cnnlabs/cnn-messaging/blob/master/src/message.js#L73 ) when receiving the message and trying to instantiate it.

**Comment by niahmiah** [comment]
Thanks for reporting this. I think instead of crashing, maybe the ideal thing to do would be set the action to the generic 'event'.

The idea was to crash intentionally on the sending end, not the receiving end. This is an unfortunate side effect.

**Comment by MDrooker** [comment]
When are we going to get this fixed?
